# Intro to PyTorch

Based on several sources:<br>
* http://deeplizard.com/
* https://pytorch.org/docs/master/

## Import library

In [1]:
# import PyTorch
import torch

In [2]:
# check version number
torch.__version__

'1.0.1.post2'

In [3]:
# check if CUDA/GPU is available
torch.cuda.is_available()

False

In [4]:
# if CUDA/GPU is available print CUDA version
if torch.cuda.is_available(): torch.version.cuda

## Create tensors

For more details see [PyTorch Tensors Explained](http://deeplizard.com/learn/video/jexkKugTg04) and [Creating PyTorch Tensors for Deep Learning](http://deeplizard.com/learn/video/AglLTlms7HU).

In [37]:
# generate tensor
t = torch.tensor([1, 2, 3]); t

tensor([1, 2, 3])

In [38]:
type(t)

torch.Tensor

In [39]:
# print list of tensor attributes
dir(t)

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__setstate_

In [67]:
# but tensor on GPU if available
if torch.cuda.is_available(): t.cuda()

In [47]:
# print important attributes
t.data, t.shape, t.dtype, t.device#, t.layout

(tensor([1, 2, 3]), torch.Size([3]), torch.int64, device(type='cpu'))

See PyTorch documentation for [torch.Tensor data types](https://pytorch.org/docs/master/tensors.html).

In [48]:
import numpy as np

In [114]:
# create dummy data
data = np.array([1,2,3]); data

array([1, 2, 3])

In [115]:
# use constructor
t1 = torch.Tensor(data); t1

tensor([1., 2., 3.])

In [116]:
# use factory function
t2 = torch.tensor(data); t2

tensor([1, 2, 3])

In [117]:
t3 = torch.as_tensor(data); t3

tensor([1, 2, 3])

In [118]:
t4 = torch.from_numpy(data); t4

tensor([1, 2, 3])

In [119]:
t1.dtype, t2.dtype, t3.dtype, t4.dtype

(torch.float32, torch.int64, torch.int64, torch.int64)

In [106]:
type(7), type(7.)

(int, float)

**The prefered option is [`torch.tensor`](https://pytorch.org/docs/master/torch.html#torch.tensor) because it uses type inference, i.e., it inferes and uses the data type of the input data.<br>Contrary, [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor) always uses the default dtype.**

In [86]:
torch.get_default_dtype()

torch.float32

In [91]:
torch.Tensor(data).dtype

torch.float32

In [93]:
torch.tensor(data).dtype

torch.int64

In [92]:
torch.tensor(data).float().dtype

torch.float32

### Other useful ways to construct tensors

In [64]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [65]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [66]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [68]:
torch.rand(2,2)

tensor([[0.8615, 0.7447],
        [0.7829, 0.1524]])

In [73]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
torch.arange(5).expand((3,5))

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

### Copy and share memory

In [120]:
data

array([1, 2, 3])

In [121]:
data[0] = 99; data

array([99,  2,  3])

In [122]:
t1, t2, t3, t4

(tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([99,  2,  3]),
 tensor([99,  2,  3]))

**Copy Data:** torch.Tensor() & torch.tensor()<br>
**Share Data:** torch.as_tensor() & torch.from_numpy() (only accepts np.arrays)

**The prefered option is [`torch.as_tensor`](https://pytorch.org/docs/master/torch.html#torch.as_tensor) because it works with several input data types, i.e., list, tuple, NumPy ndarray, scalar, and other types.**

### Rank, axes, and shapes

Optional: Refresh your knowledge of [rank, axes, and shape of tensors for deep learning](http://deeplizard.com/learn/video/AiyK0idr4uM) and look at a [CNN Tensor Shape Example](http://deeplizard.com/learn/video/k6ZF1TSniYk).

### Reshaping

In [5]:
t5 = torch.randn((3,3)); t5

tensor([[ 0.0703, -2.0433, -0.6535],
        [ 0.1943, -0.5165, -1.2701],
        [ 1.0064, -1.8182, -0.2117]])

In [6]:
t5.shape, t.size()

(torch.Size([3, 3]), torch.Size([3, 3]))

In [7]:
t5.numel()

9

In [14]:
t5.reshape(1,-1).shape

torch.Size([1, 9])

In [46]:
t5.view(9,-1).shape

torch.Size([9, 1])

[What's the difference between reshape and view in pytorch?](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch): "If you just want to reshape tensors, use torch.reshape. If you're also concerned about memory usage and want to ensure that the two tensors share the same data, use torch.view."

In [47]:
t5.view(9,-1).squeeze().shape

torch.Size([9])

In [49]:
t5.unsqueeze(dim=0).shape

torch.Size([1, 3, 3])

In [51]:
t5.unsqueeze(dim=1).shape

torch.Size([3, 1, 3])

In [57]:
t6 = torch.rand(3,4,5,6)

In [58]:
t6.shape

torch.Size([3, 4, 5, 6])

In [66]:
t6.transpose(0,-1).shape

torch.Size([6, 4, 5, 3])

In [67]:
t7 = torch.rand(28,28,3)

In [68]:
t7.shape

torch.Size([28, 28, 3])

In [69]:
t7.permute(2,0,1).shape

torch.Size([3, 28, 28])

Continue with the [deeplizard tutorials](http://deeplizard.com/learn/video/fCVuiW9AFzY).