# PyTorch 2 - torch.nn

Based on:<br>
* [torch.nn tutorial](https://pytorch.org/tutorials/beginner/nn_tutorial.html)
* [torch.nn docs](https://pytorch.org/docs/stable/nn.html)

## Imports

In [1]:
# import PyTorch
import torch

In [4]:
# check version number
torch.__version__

'1.0.1.post2'

In [2]:
import torch.nn as nn

In [5]:
# check if CUDA/GPU is available
torch.cuda.is_available()

False

In [6]:
# if CUDA/GPU is available print CUDA version
if torch.cuda.is_available(): torch.version.cuda

## torch.nn.Module

In [13]:
# create class instance
lin = nn.Linear(10,5)

In [14]:
lin

Linear(in_features=10, out_features=5, bias=True)

In [15]:
# access weights and biases
lin.weight, lin.bias

(Parameter containing:
 tensor([[ 0.0786,  0.1508, -0.2231, -0.0703, -0.1125, -0.1226,  0.1040,  0.2447,
          -0.0353,  0.3150],
         [-0.0417, -0.1711, -0.2525, -0.1121,  0.0269, -0.1992,  0.1088, -0.0654,
          -0.1672, -0.0131],
         [-0.0151,  0.1263,  0.0325, -0.1861,  0.0098,  0.1111,  0.2114, -0.2393,
           0.0044,  0.2168],
         [ 0.2788,  0.0582,  0.2022, -0.1853, -0.1113,  0.2044,  0.2381,  0.0133,
          -0.2733,  0.1778],
         [ 0.0939,  0.2405,  0.0915,  0.2111,  0.3146,  0.2002, -0.1735, -0.2658,
           0.2496, -0.0460]], requires_grad=True), Parameter containing:
 tensor([ 0.2975,  0.2421, -0.3009, -0.0732,  0.2276], requires_grad=True))

In [16]:
# add ".data" to only get the data
# .item() gets a Python number from a tensor containing a single value.
lin.weight.data

tensor([[ 0.0786,  0.1508, -0.2231, -0.0703, -0.1125, -0.1226,  0.1040,  0.2447,
         -0.0353,  0.3150],
        [-0.0417, -0.1711, -0.2525, -0.1121,  0.0269, -0.1992,  0.1088, -0.0654,
         -0.1672, -0.0131],
        [-0.0151,  0.1263,  0.0325, -0.1861,  0.0098,  0.1111,  0.2114, -0.2393,
          0.0044,  0.2168],
        [ 0.2788,  0.0582,  0.2022, -0.1853, -0.1113,  0.2044,  0.2381,  0.0133,
         -0.2733,  0.1778],
        [ 0.0939,  0.2405,  0.0915,  0.2111,  0.3146,  0.2002, -0.1735, -0.2658,
          0.2496, -0.0460]])

In [17]:
dir(lin.weight)

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__setstate_

In [21]:
# .data gets the tensor, and in combination with .numpy() an np array.
lin.weight.data.numpy()

array([[ 0.07858554,  0.15084133, -0.22308512, -0.07028814, -0.11254464,
        -0.12259689,  0.10402086,  0.24473402, -0.03530282,  0.31502452],
       [-0.0416517 , -0.17113034, -0.25251487, -0.11211117,  0.0268513 ,
        -0.19919854,  0.10884285, -0.06538936, -0.16720058, -0.01309493],
       [-0.01507956,  0.12627214,  0.03250068, -0.18611003,  0.00981596,
         0.11106732,  0.2113876 , -0.23930027,  0.00443694,  0.21682683],
       [ 0.27879736,  0.05821407,  0.2021912 , -0.18532842, -0.11128481,
         0.20442101,  0.23811814,  0.01332703, -0.27333665,  0.17784593],
       [ 0.09394956,  0.24046043,  0.09152436,  0.21105018,  0.31458953,
         0.200241  , -0.17345528, -0.26579714,  0.24961224, -0.04597169]],
      dtype=float32)

In [26]:
conv = nn.Conv2d(3,32,3)

In [30]:
conv(torch.randn(1,3,28,28)).shape

torch.Size([1, 32, 26, 26])

See [torch.nn docs](https://pytorch.org/docs/stable/nn.html) for all the options!

## Neural networks

In [38]:
my_first_neural_network = nn.Sequential(nn.Linear(64,32),nn.ReLU(),nn.Linear(32,1),nn.Sigmoid())

In [39]:
my_first_neural_network

Sequential(
  (0): Linear(in_features=64, out_features=32, bias=True)
  (1): ReLU()
  (2): Linear(in_features=32, out_features=1, bias=True)
  (3): Sigmoid()
)

In [40]:
# rund tensor through network
my_first_neural_network(torch.randn(1,64))

tensor([[0.4253]], grad_fn=<SigmoidBackward>)

In [41]:
# get the output with .item()
my_first_neural_network(torch.randn(1,64)).item()

0.46016421914100647

In [43]:
# print all the parameters and their gradients:
for name, param in my_first_neural_network.named_parameters():
    print(name,':\nparam:',param,'nparam.grad:',param.grad)

0.weight :
param: Parameter containing:
tensor([[-0.0093, -0.0463,  0.1069,  ...,  0.0947,  0.0879,  0.1144],
        [ 0.0679, -0.0387,  0.0425,  ...,  0.0414, -0.0869,  0.0283],
        [-0.0541,  0.1098, -0.1088,  ...,  0.0970, -0.0614, -0.0843],
        ...,
        [-0.0429, -0.0117,  0.0525,  ...,  0.0327,  0.0801, -0.0601],
        [-0.0794,  0.0276,  0.0595,  ..., -0.0620,  0.1090, -0.1193],
        [-0.1093, -0.0176, -0.1216,  ...,  0.0853,  0.0290, -0.0172]],
       requires_grad=True) nparam.grad: None
0.bias :
param: Parameter containing:
tensor([ 0.1182, -0.1228, -0.0830,  0.0449,  0.1234,  0.0594,  0.0204, -0.0440,
         0.0409, -0.0403, -0.0034, -0.1128,  0.1031,  0.0096,  0.1211, -0.0984,
        -0.0367,  0.0397, -0.0180, -0.0843, -0.1209,  0.0585, -0.0030,  0.0153,
         0.0799, -0.0232, -0.1071,  0.0396, -0.0454, -0.1211,  0.0824, -0.0573],
       requires_grad=True) nparam.grad: None
2.weight :
param: Parameter containing:
tensor([[ 0.0017, -0.0648, -0.0069, -

In [44]:
# easy way to get NN parameters with requires_grad == True
param_dict = {name: param for name, param in my_first_neural_network.named_parameters() if param.requires_grad}

In [45]:
param_dict

{'0.weight': Parameter containing:
 tensor([[-0.0093, -0.0463,  0.1069,  ...,  0.0947,  0.0879,  0.1144],
         [ 0.0679, -0.0387,  0.0425,  ...,  0.0414, -0.0869,  0.0283],
         [-0.0541,  0.1098, -0.1088,  ...,  0.0970, -0.0614, -0.0843],
         ...,
         [-0.0429, -0.0117,  0.0525,  ...,  0.0327,  0.0801, -0.0601],
         [-0.0794,  0.0276,  0.0595,  ..., -0.0620,  0.1090, -0.1193],
         [-0.1093, -0.0176, -0.1216,  ...,  0.0853,  0.0290, -0.0172]],
        requires_grad=True), '0.bias': Parameter containing:
 tensor([ 0.1182, -0.1228, -0.0830,  0.0449,  0.1234,  0.0594,  0.0204, -0.0440,
          0.0409, -0.0403, -0.0034, -0.1128,  0.1031,  0.0096,  0.1211, -0.0984,
         -0.0367,  0.0397, -0.0180, -0.0843, -0.1209,  0.0585, -0.0030,  0.0153,
          0.0799, -0.0232, -0.1071,  0.0396, -0.0454, -0.1211,  0.0824, -0.0573],
        requires_grad=True), '2.weight': Parameter containing:
 tensor([[ 0.0017, -0.0648, -0.0069, -0.1483, -0.0349,  0.0576, -0.1679, -0

In [61]:
# freeze all parameters in a NN
for param in my_first_neural_network.parameters():
    param.requires_grad_(False)

In [62]:
param_dict = {name: param for name, param in my_first_neural_network.named_parameters() if param.requires_grad}
param_dict

{}

In [64]:
# unfreeze the last layer with gradients
my_first_neural_network[-2].weight.requires_grad_(True);
my_first_neural_network[-2].bias.requires_grad_(True);

In [65]:
param_dict = {name: param for name, param in my_first_neural_network.named_parameters() if param.requires_grad}
param_dict

{'2.weight': Parameter containing:
 tensor([[ 0.0017, -0.0648, -0.0069, -0.1483, -0.0349,  0.0576, -0.1679, -0.0273,
           0.1307, -0.1500, -0.0868, -0.0145, -0.0899, -0.1387,  0.1403,  0.0465,
          -0.0259, -0.1112,  0.1460, -0.1460,  0.1340, -0.0861,  0.0089,  0.1072,
           0.0689,  0.1166,  0.1714, -0.1722, -0.0096, -0.1169, -0.0955,  0.0134]],
        requires_grad=True), '2.bias': Parameter containing:
 tensor([-0.0132], requires_grad=True)}

## Custom nn classes

Minimal code to sublass nn.Module in PyTorch:
```
class NewClass(nn.Module):
   def __init__(self): # overwritte constructor
      super().__init__() # call super class constructor
      ...

   def forward(self, ...):
      ...
      return ..`
```